codeProduct1, unitsProduct1, priceProduct1 = input().split()
codeProduct2, unitsProduct2, priceProduct2 = input().split()
codeProduct1 = int(codeProduct1)
unitsProduct1 = int(unitsProduct1)
priceProduct1 = float(priceProduct1)
codeProduct2 = int(codeProduct2)
unitsProduct2 = int(unitsProduct2)
priceProduct2 = float(priceProduct2)
total = (unitsProduct1 * priceProduct1) + (unitsProduct2 * priceProduct2)
print("VALOR A PAGAR: R$ %.2f" %total)
